defaults: &defaults
  adapter: mysql
  username: root
development:
  database: rmmmp_development
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: rmmmp_test
  <<: *defaults
production:
  database: rmmmp_production
  <<: *defaults
